# <center> TP N°1 </center>
### <center> Methodes Directes pour la Résolution des Systèmes Linéaires Ax = b </center>
<div>
    <center> RAZAFINDRAZAKA Henintsoa </center>
    <center> Wang James </center>
    <center> ____________</center>
    <center> ING5 SI GR02 </center>
    <center> 25/10/2020 </center>
</div>

## 1. Résolution de Tx = b avec T triangulaire inférieure

1. Ouvrir un fichier qu’on nomme `trianinf.m`. Dans ce fichier, on va créer la fonction Matlab qui à partir d’une matrice inférieure T et d’un second membre b, résout le système Tx = b. La syntaxe de début du programme est la suivante :

```
function x=trianginf(T,b)
% T est la matrice triangulaire inférieure et b le vecteur 2nd membre.
n=length(b);
x(1)=
for i=2:n
x(i)=...
end
```

In [1]:
import numpy as np

n = 4
T = np.tril(np.random.randint(10,size=(n,n)) )

while np.linalg.det(T) == 0.0: 
    T = np.tril(np.random.randint(10,size=(n,n)) )

print('T = \n',T)
print('\n|T|= ', np.linalg.det(T))

T = 
 [[5 0 0 0]
 [3 9 0 0]
 [4 3 7 0]
 [2 3 0 6]]

|T|=  1889.999999999999


In [2]:
b = np.random.randint(10, size=(n,))
print('b = ', b)

b =  [2 7 4 7]


In [3]:
def trianginf(T,b):
    n = len(b)
    x = np.zeros(b.shape)

    x[0] = b[0] / T[0][0]
    for i in range(1,n):
        sigma = 0
        for j in range(0, i):
            sigma += T[i][j] * x[j]
        x[i] = (1/T[i][i]) * ( b[i] - sigma )
    return x

x_test = trianginf(T,b)
print('Tx = ',T.dot(x_test))

Tx =  [2. 7. 4. 7.]


## 2. Résolution de Tx = b avec T triangulaire supérieure

2. Ouvrir un fichier qu’on nomme `triansup.m`. Dans ce fichier, on va créer la fonction Matlab qui à partir d’une matrice supérieure T et d’un second membre b, résout le système T x = b. La syntaxe de début du programme est la suivante :

```
function x=triangsup(T,b)
% T est la matrice triangulaire supérieure et b le vecteur 2nd membre.
n=length(b);
x(n)=
for i=n-1:-1:1 % boucle incrément négatif
x(i)=...
end
```

In [4]:
n = 4
T = np.triu(np.random.randint(10,size=(n,n)) )

while np.linalg.det(T) == 0.0: 
    T = np.tril(np.random.randint(10,size=(n,n)) )

print('T = \n',T)
print('\n|T|= ', np.linalg.det(T))

T = 
 [[1 0 0 0]
 [5 8 0 0]
 [6 1 4 0]
 [4 9 7 1]]

|T|=  31.999999999999986


In [5]:
b = np.random.randint(10, size=(n,))
print('b =',b)

b = [9 8 2 8]


In [6]:
def triangsup(T,b):
    n = len(b)
    x = np.zeros(b.shape)

    x[n-1] = b[n-1] / T[n-1][n-1]
    for i in range(n-2,-1,-1):
        sigma = 0
        for j in range(i+1, n):
            sigma += T[i][j] * x[j]
        x[i] = (1/T[i][i]) * ( b[i] - sigma )
    return x

x = triangsup(T,b)
print('Tx = ',T.dot(x))

Tx =  [ 9.  53.  57.  56.5]


## 3. Résolution de Ax = b avec A triangularisé par Gauss

3. Ouvrir un fichier qu’on nomme `gauss.m`. Dans ce fichier, on va créer la fonction Matlab qui à
partir d’une matrice A effectue de Gauss et résout le système Ax = b. La syntaxe de début du programme est la suivante :

```
function x=gauss(A,b)
% A est la matrice principale et b le vecteur second membre.
n=length(b);
.....
```

In [7]:
A = np.random.rand(n,n)
A_init = A
print('A =\n',A)
print('\n|A|= ', np.linalg.det(A))


A =
 [[0.42980311 0.00920982 0.33214023 0.01410368]
 [0.21501668 0.21602305 0.15481142 0.42912682]
 [0.62501318 0.4553875  0.83671549 0.18300378]
 [0.10164058 0.08788828 0.55580165 0.47006239]]

|A|=  0.04165987131663422


In [8]:
b_init = np.random.randint(10, size=(n,))
print('b = ',b_init)

b =  [3 8 9 4]


In [9]:
# triangulation de A
A_init = A
b = b_init
def gauss(A, b):
    m = np.zeros(A.shape)
    for k in range(0, n-1):
        for i in range(k+1, n):
            m[i][k] = A[i][k] / A[k][k]
            for j in range(k, n):
                A[i][j] = A[i][j] - m[i][k]*A[k][j]
            b[i] = b[i] - m[i][k] * b[k]
    
    x = triangsup(A,b)
    return x

x = gauss(A,b)

print("\nA_init*x = ", np.round(A.dot(x)))
print("\nb_init = ",b)



A_init*x =  [ 3.  6. -8. 10.]

b_init =  [ 3  6 -8 10]


## 4. Comparaison entre les performances de `gauss(A,b)` et `inv(A) * b`

4. Tester la méthode sur un exemple et comparer votre résultat avec celui obtenu avec la commande A/b et celui obtenu avec la commande inv(A)*b. Que se passe-t-il quand on augmente la taille de la matrice (n = 10, 100, 1000, ...).

In [10]:
import time

myround = np.vectorize(round)

n = 10
while n <= 1000 :

    A_init = np.random.rand(n,n)
    A = A_init

    b_init = np.random.randint(10, size=(n,))
    b = b_init
    
    print('\nn = ', n)
    
    start_time = time.time()
    
    # Notre gauss
    x_gauss = gauss(A_init,b_init)
    print('\n ¤ My gauss : %s seconds ' % (time.time() - start_time))
        
    start_time = time.time()
    
    # Calcul python A^(-1).b
    A_inv = np.linalg.inv(A_init)
    x_np = A_inv.dot(b_init)
    print(' ¤ A^(-1).b : %s seconds ' % (time.time() - start_time))
            
    print('\n*******************************************')
    
    n *= 10


n =  10

 ¤ My gauss : 0.0020074844360351562 seconds 
 ¤ A^(-1).b : 0.007963418960571289 seconds 

*******************************************

n =  100

 ¤ My gauss : 0.31145143508911133 seconds 
 ¤ A^(-1).b : 0.0009620189666748047 seconds 

*******************************************

n =  1000

 ¤ My gauss : 284.2725579738617 seconds 
 ¤ A^(-1).b : 0.0488431453704834 seconds 

*******************************************


> Lorsqu'on augmente la taille de la matrice n, le temps d'éxecution de la méthode de Gauss augmente exponentiellement contrairement à la méthode np.linalg.inv de Numpy. 

## 5. Factorisation A = LU

5. Ouvrir un fichier qu’on nomme `ludecomp.m`. Dans ce fichier, on va créer la fonction Matlab qui à partir d’une matrice A effectue la factorisation de type LU sous la forme A = LU. La syntaxe de début du programme est la suivante :

```
function [L,U]=ludecomp(A)
% A est la matrice principale.
n=length(b);
.....
```

In [11]:
n = 4

A = np.random.randint(10,size=(n,n))
while np.linalg.det(A) == 0:
    A = np.random.randint(10,size=(n,n))

A_init = A
print('A = \n',A)
print('\n|A|= ', np.linalg.det(A))

b = np.random.randint(10, size=(n,))
b_init = b
print('b = ',b)

A = 
 [[8 9 7 2]
 [5 3 7 6]
 [3 5 5 2]
 [5 0 8 5]]

|A|=  364.0000000000003
b =  [5 0 2 8]


In [12]:
def ludecomp(A):
    n = A.shape[0]
    L = np.zeros(A.shape)
    U = np.zeros(A.shape)
    L[0][0] = 1
    
    for j in range(0, n):
        U[0][j] = A[0][j]
        
    for i in range(1, n):
        L[i][0] = A[i][0] / U[0][0]
        
    for i in range(1, n):
        L[i][i] = 1
        s0 = 0
        for k in range(0, i):
            s0 += L[i][k] * U[k][i]
        U[i][i] = A[i][i] - s0
        
        for j in range(i, n):
            s1 = 0
            for k in range(0, i):
                s1 += L[i][k] * U[k][j]
            U[i][j] = A[i][j] - s1
            
            s2 = 0
            for k in range(0, i):
                s2 += L[j][k] * U[k][i]
            L[j][i] = (1 / U[i][i]) * (A[j][i] - s2)
    return L, U

In [13]:
L, U  = ludecomp(A)

print("A = \n", A)
print("\nL * U = \n", L.dot(U))

A = 
 [[8 9 7 2]
 [5 3 7 6]
 [3 5 5 2]
 [5 0 8 5]]

L * U = 
 [[8. 9. 7. 2.]
 [5. 3. 7. 6.]
 [3. 5. 5. 2.]
 [5. 0. 8. 5.]]


## 6. Résolution de Ax = b avec la factorisation A = LU

6. Ouvrir un fichier qu’on nomme lusovle.m. Dans ce fichier, on va créer la fonction Matlab qui à partir d’une matrice A et d’un vecteur b résout le système Ax = b à partir de la factorisation LU de la matrice A. La syntaxe de début du programme est la suivante:

```
function [L,U]=ludecomp(A)
% A est la matrice principale.
n=length(b);
.....
```

Ax = B => LUx = B => Ly = B avec Ux = y

In [14]:
y = trianginf(L,b) 
print("y = ",y)

x = triangsup(U,y)
print("\nx = ", x)

print("\nb = ", b)
print("\nA.dot(x) = ", np.round(A.dot(x)) )

y =  [ 5.         -3.125      -1.80952381 10.66666667]

x =  [ 0.65934066 -1.13736264  2.12637363 -2.46153846]

b =  [5 0 2 8]

A.dot(x) =  [5. 0. 2. 8.]


## 7. Comparaison entre les performances de `ludecomp(A)`, `lu(A)` , `gauss(A,b)` et `inv(A)*b`

7. Tester la méthode sur un exemple et comparer votre résultat avec celui obtenu avec la fonction lu déja implémenter dans Matlab (help lu), la commande A/b et celui obtenu avec la commande inv(A)*b. Que se passe-t-il quand on augmente la taille de la matrice (n = 10, 100, 1000, ...).


In [15]:
import time
import scipy.linalg

myround = np.vectorize(round)

n = 10
while n <= 1000 :

    A_init = np.random.rand(n,n)
    A = A_init

    b_init = np.random.randint(10, size=(n,))
    b = b_init
    
    print('\nn = ', n)
    
    ################## méthode lu(A) de scipy ##################
    
    start_time = time.time()
    
    P, L, U  = scipy.linalg.lu(A)
    y = trianginf(L,b) 
    x_scipy = triangsup(U,y)
    
    print(' ¤ scipy lu(A) : %s seconds ' % (time.time() - start_time))
    
    start_time = time.time()
    
    ################## méthode ludecomp(A) ##################
    
    start_time = time.time()
    
    L, U  = ludecomp(A)
    y = trianginf(L,b) 
    x_ludecomp = triangsup(U,y)
    
    print(' ¤ ludecomp(A) : %s seconds ' % (time.time() - start_time))
    
    start_time = time.time()
    
    ################## méthode gauss(A,B) ##################
    x_gauss = myround(gauss(A_init,b_init), 6)
    
    print(' ¤ gauss(A, b) : %s seconds ' % (time.time() - start_time))
    
    start_time = time.time()
    
    ################## methode inv(A) * b de numpy ##################
    A_inv = np.linalg.inv(A_init)
    x_np = myround(A_inv.dot(b), 6)
    
    print(' ¤ inv(A) * b  : %s seconds ' % (time.time() - start_time))
    
    
    
    n *= 10


n =  10
 ¤ scipy lu(A) : 0.0 seconds 
 ¤ ludecomp(A) : 0.0 seconds 
 ¤ gauss(A, b) : 0.0009968280792236328 seconds 
 ¤ inv(A) * b  : 0.0009975433349609375 seconds 

n =  100
 ¤ scipy lu(A) : 0.003988504409790039 seconds 
 ¤ ludecomp(A) : 0.19052457809448242 seconds 
 ¤ gauss(A, b) : 0.303178071975708 seconds 
 ¤ inv(A) * b  : 0.0009739398956298828 seconds 

n =  1000
 ¤ scipy lu(A) : 0.41794681549072266 seconds 
 ¤ ludecomp(A) : 183.69784784317017 seconds 
 ¤ gauss(A, b) : 293.27773666381836 seconds 
 ¤ inv(A) * b  : 0.04585146903991699 seconds 


> Lorsqu'on augmente la taille de la matrice n, les temps d'éxecution de nos méthodes de décomposition LU et 
de Gauss augmentent exponentiellement contrairement aux méthodes inverse de numpy et lu de scipy. Le temps d'éxecution de ludecomp reste tout de meme inférieur à celui de Gauss. La décomposition LU reste donc plus performante que la résolution par la méthode de Gauss.